### ISSUE TITLE
koolsoft的版本运行不起来

### ISSUE THREAD

**Issue by yulewang** [hikaruchang/udpspeeder-koolsoft#2]
我这里跑不起来。。
保存后依旧提示：【警告】：进程未运行！
grep也找不到

UDPspeeder 2.0.3
固件版本：LEDE Koolshare X64 V2.8 r5707-9f11956 by fw867

**Comment by HikaruChang** [comment]
请确认信息是否真的填写对了
![wx20180214-022447](https://user-images.githubusercontent.com/16264281/36166679-42a05b34-112e-11e8-9495-677bda8449ab.png)

**Comment by yulewang** [comment]
居然这么快收到回复！春节快乐！

本地端口设置为:7777 后成功了...

**Comment by yulewang** [comment]
居然这么快收到回复！春节快乐！

本地端口设置为:7777 后成功了...

**Comment by HikaruChang** [comment]
春節快樂
